AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/**/*'
   - 'vendor/bundle/**/*'
   - 'node_modules/**/*'
   - 'bower_components/**/*'
Rails:
  Enabled: true
